
var BOATS = {
"tug":{
    "speed":5,
    "sensors":3,
    "sensitivity":2,
    "sailors":[2],
    "height":50,
    "width":50,
    "offset":16,
    "parts":[
        {
            img:"img/boats/Tugboat_chimney.png",
            delay:4
        },
        {
            img:"img/boats/Tugboat_cabin.png",
            delay:3
        },
        {
            img:"img/boats/Tugboat_flags.png",
            delay:2
        },
        {
            img:"img/boats/Tugboat_hull.png",
            delay:0,
            sailors:[{x:12,y:18},{x:19,y:17},{x:27,y:13},{x:33,y:10},{x:41,y:10}]
        },
        {
            img:"img/boats/Tugboat_lifesaver.png",
            delay:2
        }
    ]
},
"pirate":{
    "speed":7,
    "sensors":4,
    "sensitivity":2,
    "sailors":[4],
    "height":50,
    "width":50,
    "offset":20,
    "parts":[
        {
            img:"img/boats/Pirate_mast.png",
            delay:3,
            sailors:[{x:24,y:38}]
        },
        {
            img:"img/boats/Pirate_hull.png",
            delay:0,
            sailors:[{x:23,y:4}]
        },
        {
            img:"img/boats/Pirate_gold.png",
            delay:1,
            sailors:[{x:11,y:13},{x:31,y:15},{x:37,y:15}]
        },
        {
            img:"img/boats/Pirate_cannons.png",
            delay:1
        },
        {
            img:"img/boats/Pirate_sail.png",
            delay:4
        }
    ]
},
"fishboat":{
    "speed":8,
    "sensors":3,
    "sensitivity":2,
    "sailors":[1],
    "height":50,
    "width":50,
    "offset":14,
    "parts":[
        {
            img:"img/boats/Fish_hull1.png",
            delay:0
        },
        {
            img:"img/boats/Fish_hull2.png",
            delay:1,
            sailors:[{x:11,y:11},{x:20,y:11},{x:30,y:11},{x:40,y:11}]
        },
        {
            img:"img/boats/Fish_cabin.png",
            delay:2
        },
        {
            img:"img/boats/Fish_chimney.png",
            delay:3
        },
        {
            img:"img/boats/Fish_smoke1.png",
            delay:4
        }
    ]
},
"barrel":{
    "speed":10,
    "sensors":1,
    "sensitivity":2,
    "sailors":[1],
    "height":50,
    "width":50,
    "offset":0,
    "parts":[
        {
            img:"img/boats/Barrel_bottom.png",
            delay:0
        },
        {
            img:"img/boats/Barrel_bottom2.png",
            delay:1
        },
        {
            img:"img/boats/Barrel_top2.png",
            delay:3
        },
        {
            img:"img/boats/Barrel_top.png",
            delay:4
        },
        {
            img:"img/boats/Barrel_middle.png",
            delay:2,
            sailors:[{x:19,y:6},{x:23,y:7},{x:28,y:6}]
        }
    ]
},
"titanic":{
    "speed":3,
    "sensors":5,
    "sensitivity":2,
    "sailors":[5],
    "offset":15,
    "width":160,
    "height":50,
    "parts":[
        {
            img:"img/boats/titanic_bottom.png",
            delay:0
        },
        {
            img:"img/boats/titanic_middle.png",
            delay:1
        },
        {
            img:"img/boats/titanic_top.png",
            delay:2,
            sailors:[{x:19,y:18},{x:29,y:18},{x:39,y:18},{x:49,y:18},{x:59,y:18}]
        },
        {
            img:"img/boats/titanic_ch1.png",
            delay:3
        },
        {
            img:"img/boats/titanic_ch2.png",
            delay:4
        },
        {
            img:"img/boats/titanic_ch3.png",
            delay:5
        },
        {
            img:"img/boats/titanic_ch4.png",
            delay:6
        }
    ]
},
"rowboat":{
    "speed":11,
    "sensors":1,
    "sensitivity":2,
    "sailors":[1],
    "height":20,
    "width":20,
    "offset":0,
    "parts":[ 
        {
            img:"img/boats/Row_bottom.png",
            delay:0
        },
        {
            img:"img/boats/Row_bottom_m.png",
            delay:1
        },
        {
            img:"img/boats/Row_top_m.png",
            delay:2,
            sailors:[{x:10,y:5}]
        },
        {
            img:"img/boats/Row_top.png",
            delay:3
        }
   ]           
},    
"tube":{
    "speed":5,
    "sensors":1,
    "sensitivity":2,
    "sailors":[1],
    "height":50,
    "width":50,
    "offset":0,
    "parts":[
        {
            img:"img/boats/Tube_back.png",
            delay:0,
            sailors:[{x:25,y:3}]
        },
        {
            img:"img/boats/Tube_front.png",
            delay:0
        },
        {
            img:"img/boats/Tube_head.png",
            delay:1
        }
    ]
},
};
