
var BOATS = {
"tug":{
    "speed":5,
    "sensors":3,
    "sensitivity":2,
    "sailors":[1,1,2,3,4,5,1,2,3,4,5],
    "height":50,
    "width":50,
    "offset":16,
    "parts":[
        {
            img:"img/boats/Tugboat_chimney.png",
            delay:4
        },
        {
            img:"img/boats/Tugboat_cabin.png",
            delay:3
        },
        {
            img:"img/boats/Tugboat_flags.png",
            delay:2
        },
        {
            img:"img/boats/Tugboat_hull.png",
            delay:0,
            sailors:[{x:12,y:18},{x:19,y:17},{x:27,y:13},{x:33,y:10},{x:41,y:10}]
        },
        {
            img:"img/boats/Tugboat_lifesaver.png",
            delay:2
        }
    ]
},
"pirate":{
    "speed":12,
    "sensors":4,
    "sensitivity":2,
    "sailors":[4,3,4,2,4],
    "height":50,
    "width":50,
    "offset":20,
    "parts":[
        {
            img:"img/boats/Pirate_mast.png",
            delay:3,
            sailors:[{x:24,y:38}]
        },
        {
            img:"img/boats/Pirate_hull.png",
            delay:0,
            sailors:[{x:23,y:4}]
        },
        {
            img:"img/boats/Pirate_gold.png",
            delay:1,
            sailors:[{x:11,y:13},{x:31,y:15},{x:37,y:15}]
        },
        {
            img:"img/boats/Pirate_cannons.png",
            delay:1
        },
        {
            img:"img/boats/Pirate_sail.png",
            delay:4
        }
    ]
},
"fish":{
    "speed":8,
    "sensors":3,
    "sensitivity":3,
    "sailors":[1,2,3,4,3,4,2,4],
    "height":50,
    "width":50,
    "offset":14,
    "parts":[
        {
            img:"img/boats/Fish_hull1.png",
            delay:0
        },
        {
            img:"img/boats/Fish_hull2.png",
            delay:1,
            sailors:[{x:11,y:11},{x:20,y:11},{x:30,y:11},{x:40,y:11}]
        },
        {
            img:"img/boats/Fish_cabin.png",
            delay:2
        },
        {
            img:"img/boats/Fish_chimney.png",
            delay:3
        },
        {
            img:"img/boats/Fish_smoke1.png",
            delay:4
        }
    ]
},
"barrel":{
    "speed":10,
    "sensors":1,
    "sensitivity":3,
    "sailors":[1,1,2,2,3],
    "height":50,
    "width":50,
    "offset":10,
    "parts":[
        {
            img:"img/boats/Barrel_bottom.png",
            delay:0
        },
        {
            img:"img/boats/Barrel_bottom2.png",
            delay:1
        },
        {
            img:"img/boats/Barrel_top2.png",
            delay:3
        },
        {
            img:"img/boats/Barrel_top.png",
            delay:4
        },
        {
            img:"img/boats/Barrel_middle.png",
            delay:2,
            sailors:[{x:19,y:18},{x:23,y:18},{x:28,y:18}]
        }
    ]
},
"titanic":{
    "speed":8,
    "sensors":5,
    "sensitivity":1,
    "sailors":[0],
    "offset":15,
    "parts":[
        {
            img:"img/boat_titanic.png",
            delay:0
        }
    ]
},
"tube":{
    "speed":50,
    "sensors":1,
    "sensitivity":3,
    "sailors":[1],
    "height":50,
    "width":50,
    "offset":0,
    "parts":[
        {
            img:"img/boats/Tube_back.png",
            delay:0,
            sailors:[{x:25,y:42}]
        },
        {
            img:"img/boats/Tube_front.png",
            delay:0
        },
        {
            img:"img/boats/Tube_head.png",
            delay:1
        }
    ]
},
};
